version: "3"

services:

  node:
    image: node:16

    container_name: DockerXP
    
    tty: true
   
    stdin_open: true
   
    command: bash
    
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      EXPRESS_PORT: 3001


  db:
    container_name: xp_wallet
    image: mysql:8.0.21
    restart: always
   
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

